# Generated by Django 2.0.8 on 2018-10-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20181024_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followpage',
            name='url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
