# Generated by Django 2.0.8 on 2018-10-25 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20181025_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followpage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_following_page', to=settings.AUTH_USER_MODEL),
        ),
    ]
