# Generated by Django 2.0.8 on 2018-10-25 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20181025_0812'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pagesanswer',
            unique_together={('question', 'answer')},
        ),
        migrations.AlterUniqueTogether(
            name='pagesquestion',
            unique_together={('page', 'question')},
        ),
    ]
