# Generated by Django 2.0.8 on 2018-10-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profession',
            field=models.TextField(blank=True, max_length=120, null=True),
        ),
    ]
