# Generated by Django 2.0.8 on 2018-10-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activation_key',
            field=models.TextField(blank=True, max_length=120, null=True),
        ),
    ]
