# Generated by Django 2.0.8 on 2018-10-17 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181017_0555'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TempPages',
        ),
    ]
