# Generated by Django 2.0.8 on 2018-10-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_temppages'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempPages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutme', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
