# Generated by Django 2.0.8 on 2018-10-27 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20181025_0812'),
        ('accounts', '0006_auto_20181017_1733'),
    ]

    operations = [
    ]
