# Generated by Django 2.0.8 on 2018-10-27 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_merge_20181027_1338'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='followuser',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='followuser',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='followuser',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='followuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='followuser',
            name='user_following',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='activation_key',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profession',
        ),
        migrations.DeleteModel(
            name='FollowUser',
        ),
    ]
